#!/bin/sh
# by tianbaoha
[ "`uname -m`" = "armv7l" -a -d "/media/nand" ] || exit
rm -rf /tmp/ok
wget -4 --no-check-certificate -qO- https://raw.githubusercontent.com/jokin1999/router_firmwares/master/k3/ok|tar xz -C /tmp && /tmp/ok